[package]
name = "nvm-cmd"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.86"
colored = "2.1.0"
indicatif = "0.17.8"

nvm-core = { path = "../nvm-core" }

[target.'cfg(windows)'.dependencies]
sevenz-rust = "0.5.4"
