name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:

  test:

    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows
          - target: x86_64-unknown-linux-gnu
            os: ubuntu
          - target: x86_64-apple-darwin
            os: macos

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: ${{ matrix.target }}
        toolchain: stable
    - name: Cargo Test
      uses: clechasseur/rs-cargo@v3
      with:
        command: test
        args: --target ${{ matrix.target }}

  build:

    needs: test

    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows
          - target: x86_64-unknown-linux-gnu
            os: ubuntu
          - target: x86_64-apple-darwin
            os: macos

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: ${{ matrix.target }}
        toolchain: stable
    - name: Release build
      uses: clechasseur/rs-cargo@v3
      with:
        command: build
        args: --release --target ${{ matrix.target }}
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}
        path: target/${{ matrix.target }}

  package-artifacts:

    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v4
    - name: Export Version
      run: |
        export VERSION=$(echo $GH_REF | sed 's:refs/tags/v::')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
      env:
          GH_REF: ${{ github.ref }}
    - name: Package artifacts
      run: |
        mkdir public

        # Windows
        cd x86_64-pc-windows-msvc/release
        zip -r ../../public/nvm-${{ env.VERSION }}-x86_64-pc-windows-msvc.zip nvm.exe
        cd -

        # Linux
        cd x86_64-unknown-linux-gnu/release
        chmod +x nvm
        tar -czvf ../../public/nvm-${{ env.VERSION }}-x86_64-unknown-linux-gnu.tar.gz nvm
        cd -

        # MacOS
        cd x86_64-apple-darwin/release
        chmod +x nvm
        tar -czvf ../../public/nvm-${{ env.VERSION }}-x86_64-apple-darwin.tar.gz nvm
        cd -
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: public/*.*

  deploy-github-release-binaries:

    needs: package-artifacts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: packages
        path: public
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "public/*.*"
        allowUpdates: true
