name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:

  test:

    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows
          - target: x86_64-unknown-linux-gnu
            os: ubuntu
          - target: x86_64-apple-darwin
            os: macos

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: ${{ matrix.target }}
        toolchain: stable
    - name: Cargo Test
      uses: clechasseur/rs-cargo@v3
      with:
        command: test
        args: --target ${{ matrix.target }}

  build:

    needs: test

    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows
            ext: .zip
          - target: x86_64-unknown-linux-gnu
            os: ubuntu
            ext: .tar.gz
          - target: x86_64-apple-darwin
            os: macos
            ext: .tar.gz

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: ${{ matrix.target }}
        toolchain: stable
    - name: Release build
      uses: clechasseur/rs-cargo@v3
      with:
        command: build
        args: --release --target ${{ matrix.target }}

    - name: Pack for Windows
      if: ${{ matrix.os }} == 'windows'
      run: |
        cd target/${{ matrix.target }}/release
        zip -r ../../../nvm-${{ env.VERSION }}-${{ matrix.target }}${{ matrix.ext }} nvm.exe
        cd -
    - name: Pack for Linux and MacOS
      if: ${{ matrix.os }} != 'windows'
      run: |
        cd target/${{ matrix.target }}/release
        chmod +x nvm
        tar -czvf ../../../nvm-${{ env.VERSION }}-${{ matrix.target }}${{ matrix.ext }} nvm
        cd -

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}
        path: nvm-${{ env.VERSION }}-${{ matrix.target }}${{ matrix.ext }}

  deploy-github-release-binaries:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v4
    - uses: ncipollo/release-action@v1
